### ISSUE TITLE
Drupal Log in

### ISSUE THREAD

**Issue by canasa21** [drupalwxt/helm-drupal#99]
Hello, we had another team install Drupal in Azure but did not provide our team with credentials. Examining the Azure YAML file the user name is listed as admin and the password is commented out. Would it have been possible to install drupalwxt/helm-drupal with those defaults? I'm not familiar with Drupal in Azure but I would imagine they could simply redeploy the YAML file? Thank you.

**Comment by sylus** [comment]
Hi @canasa21 you mean they install this helm chart in AKS?

By default we don't provide a password since when that var is left empty. Instead it will be auto generated if that variable is not set. Usually people would leverage their CI/CD solutions to set this variable via an environment variable passed.

https://github.com/drupalwxt/helm-drupal/blob/master/drupal/templates/secret/drupal.yaml#L20

You can always login to the container and run `drush uli` to reset your password as well.
